// Code generated by hertz generator.

package cookie

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"integration/pkg/constant"
	"integration/pkg/hertz/biz/handler"
	"integration/pkg/hertz/biz/model/api/cookie"
	"integration/pkg/hertz/biz/model/api/infisical"
	"integration/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/emicklei/go-restful/v3"
	"k8s.io/klog/v2"
)

// GetCookie .
// @router /api/cookie/retrieve [POST]
func GetCookie(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cookie.CookieReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	var data = make(map[string]string)
	data["name"] = fmt.Sprintf("cookie:%s:%s", req.Domain, req.User) // doamin: .xxx.com
	data["env"] = constant.Environment
	var infisicalUrl = fmt.Sprintf("%s:8080/RetrieveSecret?workspace=%s", constant.InfisicalAddr, constant.Workspace)

	resp, err := utils.RestClient.R().SetHeader(restful.HEADER_ContentType, restful.MIME_JSON).
		SetHeader(constant.HeaderUserName, req.User).
		SetBody(data).
		SetResult(&infisical.InfisicalResp{}).
		Post(infisicalUrl)

	if err != nil {
		klog.Errorf("GetCookie failed, request error: %v, domain: %s", err, req.Domain)
		handler.ErrorResponse(c, err)
		return
	}

	if resp.StatusCode() != http.StatusOK {
		klog.Errorf("GetCookie failed, status code: %d, resp: %s", resp.StatusCode(), string(resp.Body()))
		handler.ErrorResponse(c, fmt.Errorf("request invalid, status code: %d", resp.StatusCode()))
		return
	}

	cookieResp := resp.Result().(*infisical.InfisicalResp)

	var resultData = make([]*cookie.CookieRespData, 0)
	var result = &cookie.CookieResp{
		Code: 0,
		Data: resultData,
	}

	if cookieResp.Code != 0 {
		err := handler.FormatErrorMessage(cookieResp.Message)
		klog.Errorf("GetCookie failed, format error: %v, content: %s", err, cookieResp.Message)
		handler.SuccessResponse(c, result)
		return
	}

	var cookieData *infisical.CookieData
	if err := json.Unmarshal([]byte(cookieResp.Data.Value), &cookieData); err != nil {
		klog.Errorf("GetCookie failed, unmarshal error: %v, content: %s", err, cookieResp.Data.Value)
		handler.SuccessResponse(c, result)
		return
	}

	var records []*cookie.CookieRespDataRaw
	for _, record := range cookieData.Records {
		var r = &cookie.CookieRespDataRaw{
			Domain:   record.Domain,
			Name:     record.Name,
			Value:    record.Value,
			Expires:  record.Expires,
			Path:     record.Path,
			Secure:   record.Secure,
			HttpOnly: record.HttpOnly,
			SameSite: record.SameSite,
			Other:    record.Other,
		}
		records = append(records, r)
	}

	result.Data = append(result.Data, &cookie.CookieRespData{
		Domain:  cookieData.Domain,
		Account: cookieData.Account,
		Records: records,
	})

	handler.SuccessResponse(c, result)
}
