FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN cd packages/app && npm run build:desktop
RUN cd packages/app && npm run build:settings
RUN cd packages/app && npm run build:market
RUN cd packages/app && npm run build:files
RUN cd packages/app && npm run build:share
RUN cd packages/app && npm run build:dashboard
RUN cd packages/app && npm run build:hub

FROM nginx:stable-alpine
COPY --from=builder /app/packages/app/dist/apps/ /apps/
COPY docker/system-frontend/nginx/*.conf /apps/nginxs/
EXPOSE 80
CMD ["nginx"]
