apiVersion: v1
entries:
  acestepv2-1.0.12:
  - urls:
    - acestepv2-1.0.12.tgz
  acestepv3-1.0.7:
  - urls:
    - acestepv3-1.0.7.tgz
  affine-1.0.14:
  - urls:
    - affine-1.0.14.tgz
  alist-1.0.5:
  - urls:
    - alist-1.0.5.tgz
  anythingllm-1.0.13:
  - urls:
    - anythingllm-1.0.13.tgz
  appsmith-1.0.6:
  - urls:
    - appsmith-1.0.6.tgz
  astral-1.0.10:
  - urls:
    - astral-1.0.10.tgz
  astrbot-1.0.4:
  - urls:
    - astrbot-1.0.4.tgz
  audiobookshelf-1.0.9:
  - urls:
    - audiobookshelf-1.0.9.tgz
  awesomedigitalhuman-1.0.4:
  - urls:
    - awesomedigitalhuman-1.0.4.tgz
  bazarr-1.0.9:
  - urls:
    - bazarr-1.0.9.tgz
  bisheng-1.0.10:
  - urls:
    - bisheng-1.0.10.tgz
  blinko-1.0.8:
  - urls:
    - blinko-1.0.8.tgz
  bytebase-1.0.8:
  - urls:
    - bytebase-1.0.8.tgz
  calendar-1.0.1:
  - urls:
    - calendar-1.0.1.tgz
  calibre-1.0.6:
  - urls:
    - calibre-1.0.6.tgz
  calibreweb-1.0.9:
  - urls:
    - calibreweb-1.0.9.tgz
  chaosmesh-0.0.7:
  - urls:
    - chaosmesh-0.0.7.tgz
  chinesesubfinder-1.0.7:
  - urls:
    - chinesesubfinder-1.0.7.tgz
  chromium-1.0.6:
  - urls:
    - chromium-1.0.6.tgz
  cloudreve-1.0.11:
  - urls:
    - cloudreve-1.0.11.tgz
  cmproxy-1.0.9:
  - urls:
    - cmproxy-1.0.9.tgz
  coder-1.0.8:
  - urls:
    - coder-1.0.8.tgz
  codeserver-1.0.7:
  - urls:
    - codeserver-1.0.7.tgz
  comfyui-1.1.8:
  - urls:
    - comfyui-1.1.8.tgz
  comfyuiclient-1.0.8:
  - urls:
    - comfyuiclient-1.0.8.tgz
  comfyuishare-1.2.32:
  - urls:
    - comfyuishare-1.2.32.tgz
  comfyuisharev2-1.0.23:
  - urls:
    - comfyuisharev2-1.0.23.tgz
  cosyvoice-1.0.12:
  - urls:
    - cosyvoice-1.0.12.tgz
  deerflow-1.0.9:
  - urls:
    - deerflow-1.0.9.tgz
  deluge-1.0.7:
  - urls:
    - deluge-1.0.7.tgz
  dify-1.1.29:
  - urls:
    - dify-1.1.29.tgz
  difyfusion-1.0.8:
  - urls:
    - difyfusion-1.0.8.tgz
  difyfusionclient-1.0.9:
  - urls:
    - difyfusionclient-1.0.9.tgz
  difyv2-1.0.5:
  - urls:
    - difyv2-1.0.5.tgz
  directus-1.0.17:
  - urls:
    - directus-1.0.17.tgz
  docmost-1.0.10:
  - urls:
    - docmost-1.0.10.tgz
  documenso-1.0.9:
  - urls:
    - documenso-1.0.9.tgz
  duplicati-1.0.10:
  - urls:
    - duplicati-1.0.10.tgz
  echomimicv2-1.0.6:
  - urls:
    - echomimicv2-1.0.6.tgz
  excalidraw-1.0.8:
  - urls:
    - excalidraw-1.0.8.tgz
  facefusion-1.0.9:
  - urls:
    - facefusion-1.0.9.tgz
  farcasterhubble-1.0.7:
  - urls:
    - farcasterhubble-1.0.7.tgz
  fastgpt-1.0.11:
  - urls:
    - fastgpt-1.0.11.tgz
  filebrowser-1.0.1:
  - urls:
    - filebrowser-1.0.1.tgz
  firecrawl-1.0.13:
  - urls:
    - firecrawl-1.0.13.tgz
  firefox-1.0.11:
  - urls:
    - firefox-1.0.11.tgz
  flowise-1.0.9:
  - urls:
    - flowise-1.0.9.tgz
  focalboard-1.0.3:
  - urls:
    - focalboard-1.0.3.tgz
  funclip-1.0.10:
  - urls:
    - funclip-1.0.10.tgz
  gaianetai-1.0.2:
  - urls:
    - gaianetai-1.0.2.tgz
  gaianetaiclient-1.0.2:
  - urls:
    - gaianetaiclient-1.0.2.tgz
  geth-1.0.7:
  - urls:
    - geth-1.0.7.tgz
  ghost-1.0.10:
  - urls:
    - ghost-1.0.10.tgz
  gitea-1.0.8:
  - urls:
    - gitea-1.0.8.tgz
  gitlabfusion-1.0.5:
  - urls:
    - gitlabfusion-1.0.5.tgz
  gitlabfusionclient-1.0.3:
  - urls:
    - gitlabfusionclient-1.0.3.tgz
  gitlabpure-1.0.7:
  - urls:
    - gitlabpure-1.0.7.tgz
  halo-1.1.20:
  - urls:
    - halo-1.1.20.tgz
  hasura-1.0.7:
  - urls:
    - hasura-1.0.7.tgz
  heygem-1.0.13:
  - urls:
    - heygem-1.0.13.tgz
  homeassistant-1.0.13:
  - urls:
    - homeassistant-1.0.13.tgz
  hoppscotch-1.0.11:
  - urls:
    - hoppscotch-1.0.11.tgz
  hunyuan3d-1.0.3:
  - urls:
    - hunyuan3d-1.0.3.tgz
  hunyuan3dclient-1.0.2:
  - urls:
    - hunyuan3dclient-1.0.2.tgz
  hunyuan3dv21-1.0.10:
  - urls:
    - hunyuan3dv21-1.0.10.tgz
  hunyuan3dv21v2-1.0.6:
  - urls:
    - hunyuan3dv21v2-1.0.6.tgz
  immich-1.0.23:
  - urls:
    - immich-1.0.23.tgz
  ipfs-1.0.6:
  - urls:
    - ipfs-1.0.6.tgz
  jaaz-1.0.13:
  - urls:
    - jaaz-1.0.13.tgz
  jaegerclient-1.0.9:
  - urls:
    - jaegerclient-1.0.9.tgz
  jellyfin-1.0.10:
  - urls:
    - jellyfin-1.0.10.tgz
  jsonhero-1.0.3:
  - urls:
    - jsonhero-1.0.3.tgz
  komga-1.0.7:
  - urls:
    - komga-1.0.7.tgz
  langbot-1.0.5:
  - urls:
    - langbot-1.0.5.tgz
  langfuse-1.0.5:
  - urls:
    - langfuse-1.0.5.tgz
  leantime-1.0.3:
  - urls:
    - leantime-1.0.3.tgz
  lidarr-1.0.6:
  - urls:
    - lidarr-1.0.6.tgz
  listmonk-1.0.7:
  - urls:
    - listmonk-1.0.7.tgz
  llamafactory-1.0.11:
  - urls:
    - llamafactory-1.0.11.tgz
  lobechat-1.0.8:
  - urls:
    - lobechat-1.0.8.tgz
  localai-1.0.11:
  - urls:
    - localai-1.0.11.tgz
  louter-0.2.0:
  - urls:
    - louter-0.2.0.tgz
  mastodon-1.0.13:
  - urls:
    - mastodon-1.0.13.tgz
  mattermost-1.0.6:
  - urls:
    - mattermost-1.0.6.tgz
  maxkb-1.0.9:
  - urls:
    - maxkb-1.0.9.tgz
  md-1.0.7:
  - urls:
    - md-1.0.7.tgz
  memos-1.0.9:
  - urls:
    - memos-1.0.9.tgz
  metabase-1.0.13:
  - urls:
    - metabase-1.0.13.tgz
  migpt-1.0.9:
  - urls:
    - migpt-1.0.9.tgz
  migpttts-1.0.6:
  - urls:
    - migpttts-1.0.6.tgz
  mindmap-1.0.13:
  - urls:
    - mindmap-1.0.13.tgz
  miniflux-1.0.16:
  - urls:
    - miniflux-1.0.16.tgz
  mongodb-6.0.24:
  - urls:
    - mongodb-6.0.24.tgz
  mtranserver-1.0.9:
  - urls:
    - mtranserver-1.0.9.tgz
  n8n-1.0.14:
  - urls:
    - n8n-1.0.14.tgz
  navidrome-1.0.8:
  - urls:
    - navidrome-1.0.8.tgz
  netdata-1.0.9:
  - urls:
    - netdata-1.0.9.tgz
  nextcloud-1.0.11:
  - urls:
    - nextcloud-1.0.11.tgz
  nocobase-1.0.6:
  - urls:
    - nocobase-1.0.6.tgz
  nocodb-1.0.9:
  - urls:
    - nocodb-1.0.9.tgz
  nostream-1.0.9:
  - urls:
    - nostream-1.0.9.tgz
  novella-1.0.8:
  - urls:
    - novella-1.0.8.tgz
  nzbget-1.0.7:
  - urls:
    - nzbget-1.0.7.tgz
  obsidian-1.0.11:
  - urls:
    - obsidian-1.0.11.tgz
  odoo-1.0.12:
  - urls:
    - odoo-1.0.12.tgz
  ollamav2-1.0.16:
  - urls:
    - ollamav2-1.0.16.tgz
  onlyoffice-1.0.10:
  - urls:
    - onlyoffice-1.0.10.tgz
  openedaispeech-1.0.12:
  - urls:
    - openedaispeech-1.0.12.tgz
  openllm-1.0.1:
  - urls:
    - openllm-1.0.1.tgz
  openwebui-1.0.23:
  - urls:
    - openwebui-1.0.23.tgz
  otmoiclp-2.5.5:
  - urls:
    - otmoiclp-2.5.5.tgz
  otmoicrelay-1.0.1:
  - urls:
    - otmoicrelay-1.0.1.tgz
  owncast-1.0.7:
  - urls:
    - owncast-1.0.7.tgz
  pdfmathtranslate-1.0.10:
  - urls:
    - pdfmathtranslate-1.0.10.tgz
  penpot-1.0.10:
  - urls:
    - penpot-1.0.10.tgz
  perplexica-1.1.15:
  - urls:
    - perplexica-1.1.15.tgz
  photoprism-1.0.13:
  - urls:
    - photoprism-1.0.13.tgz
  photoview-1.0.8:
  - urls:
    - photoview-1.0.8.tgz
  plane-1.0.9:
  - urls:
    - plane-1.0.9.tgz
  prometheusclient-1.0.9:
  - urls:
    - prometheusclient-1.0.9.tgz
  prowlarr-1.0.8:
  - urls:
    - prowlarr-1.0.8.tgz
  qbittorrent-1.0.17:
  - urls:
    - qbittorrent-1.0.17.tgz
  qinglong-0.0.5:
  - urls:
    - qinglong-0.0.5.tgz
  radarr-1.0.7:
  - urls:
    - radarr-1.0.7.tgz
  radicale-1.0.4:
  - urls:
    - radicale-1.0.4.tgz
  ragflow-1.0.20:
  - urls:
    - ragflow-1.0.20.tgz
  rallly-1.0.8:
  - urls:
    - rallly-1.0.8.tgz
  readarr-1.0.7:
  - urls:
    - readarr-1.0.7.tgz
  redroid-1.0.10:
  - urls:
    - redroid-1.0.10.tgz
  refly-1.0.10:
  - urls:
    - refly-1.0.10.tgz
  rsshub-1.0.8:
  - urls:
    - rsshub-1.0.8.tgz
  sdwebui-1.0.12:
  - urls:
    - sdwebui-1.0.12.tgz
  sdwebuiclient-1.0.4:
  - urls:
    - sdwebuiclient-1.0.4.tgz
  sdwebuiforge-1.0.4:
  - urls:
    - sdwebuiforge-1.0.4.tgz
  sdwebuiforgeforcluster-1.0.6:
  - urls:
    - sdwebuiforgeforcluster-1.0.6.tgz
  sdwebuiforgeneov2-1.0.2:
  - urls:
    - sdwebuiforgeneov2-1.0.2.tgz
  sdwebuiforgeshare-1.0.12:
  - urls:
    - sdwebuiforgeshare-1.0.12.tgz
  sdwebuishare-1.0.19:
  - urls:
    - sdwebuishare-1.0.19.tgz
  sdwebuisharev2-1.0.6:
  - urls:
    - sdwebuisharev2-1.0.6.tgz
  sealcaster-1.0.1:
  - urls:
    - sealcaster-1.0.1.tgz
  searxng-1.0.13:
  - urls:
    - searxng-1.0.13.tgz
  searxngclient-1.0.4:
  - urls:
    - searxngclient-1.0.4.tgz
  searxngv2-1.0.6:
  - urls:
    - searxngv2-1.0.6.tgz
  seatable-1.0.19:
  - urls:
    - seatable-1.0.19.tgz
  secondme-1.0.9:
  - urls:
    - secondme-1.0.9.tgz
  showdoc-1.0.11:
  - urls:
    - showdoc-1.0.11.tgz
  sickchill-1.0.10:
  - urls:
    - sickchill-1.0.10.tgz
  sonarr-1.0.9:
  - urls:
    - sonarr-1.0.9.tgz
  stablefast3d-1.0.6:
  - urls:
    - stablefast3d-1.0.6.tgz
  stablefast3dclient-1.0.2:
  - urls:
    - stablefast3dclient-1.0.2.tgz
  stablefast3dshare-1.0.10:
  - urls:
    - stablefast3dshare-1.0.10.tgz
  steamheadless-1.0.28:
  - urls:
    - steamheadless-1.0.28.tgz
  stirlingpdf-1.0.7:
  - urls:
    - stirlingpdf-1.0.7.tgz
  studio-1.0.46:
  - urls:
    - studio-1.0.46.tgz
  teable-1.0.12:
  - urls:
    - teable-1.0.12.tgz
  transmission-1.0.8:
  - urls:
    - transmission-1.0.8.tgz
  uptimekuma-1.0.5:
  - urls:
    - uptimekuma-1.0.5.tgz
  wewerss-1.0.15:
  - urls:
    - wewerss-1.0.15.tgz
  whisper-1.0.4:
  - urls:
    - whisper-1.0.4.tgz
  whisperclient-1.0.2:
  - urls:
    - whisperclient-1.0.2.tgz
  whisperservicev2-1.0.3:
  - urls:
    - whisperservicev2-1.0.3.tgz
  whisperwebui-1.0.14:
  - urls:
    - whisperwebui-1.0.14.tgz
  whisperwebuiv2-1.0.3:
  - urls:
    - whisperwebuiv2-1.0.3.tgz
  windows-1.1.1:
  - urls:
    - windows-1.1.1.tgz
  wise-1.1.49:
  - urls:
    - wise-1.1.49.tgz
  wordpress-1.0.15:
  - urls:
    - wordpress-1.0.15.tgz
  wordpresspure-1.1.7:
  - urls:
    - wordpresspure-1.1.7.tgz
  xinference-1.0.17:
  - urls:
    - xinference-1.0.17.tgz
  xinferencev2-1.0.5:
  - urls:
    - xinferencev2-1.0.5.tgz
