---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: packalares-platform
  labels:
    app: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        args:
        - redis-server
        - --requirepass
        - "57663c0bf6836c0d3429465bd3f65144"
        - --maxmemory-policy
        - noeviction
        - --appendonly
        - "yes"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - "57663c0bf6836c0d3429465bd3f65144"
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - "57663c0bf6836c0d3429465bd3f65144"
            - ping
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: data
        hostPath:
          path: /var/lib/packalares/redis-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: packalares-platform
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
