import { defineStore } from 'pinia';

export const useMonitorStore = defineStore('monitor', {
  state: () => ({
    cpu: { ratio: 0, total: 0, usage: 0 },
    memory: { ratio: 0, total: 0, usage: 0 },
    disk: { ratio: 0, total: 0, usage: 0 },
    gpu: { ratio: 0, total: 0, usage: 0 },
    cpuUsage: 0,
    cpuFreqMHz: 0,
    memUsed: 0,
    memTotal: 0,
    swapUsed: 0,
    swapTotal: 0,
    diskUsed: 0,
    diskTotal: 0,
    diskRead: 0,
    diskWrite: 0,
    netRx: 0,
    netTx: 0,
    tempCPU: 0,
    tempGPU: 0,
    tempNVMe: 0,
    powerCPU: 0,
    powerGPU: 0,
    powerTotal: 0,
    fans: [] as Array<{ name: string; rpm: number }>,
    gpuName: '',
    gpuUtil: 0,
    gpuMemUsed: 0,
    gpuMemTotal: 0,
    gpuTemp: 0,
    gpuPowerDraw: 0,
    gpuPowerLimit: 0,
    uptime: 0,
    load: [0, 0, 0],
    weather: {
      temperature: 0,
      icon: '',
      description: '',
      city: '',
      country: '',
      windSpeed: 0,
    },
  }),
});
