FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN cd packages/app && npm run build:wizard

FROM nginx:stable-alpine
RUN sed -i '1idaemon off;' /etc/nginx/nginx.conf
COPY docker/wizard/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/packages/app/dist/spa/ /app
EXPOSE 80
CMD ["nginx"]
