/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "kubesphere.io/api/iam/v1alpha2"
)

// FakeSyncs implements SyncInterface
type FakeSyncs struct {
	Fake *FakeIamV1alpha2
}

var syncsResource = schema.GroupVersionResource{Group: "iam.kubesphere.io", Version: "v1alpha2", Resource: "syncs"}

var syncsKind = schema.GroupVersionKind{Group: "iam.kubesphere.io", Version: "v1alpha2", Kind: "Sync"}

// Get takes name of the sync, and returns the corresponding sync object, and an error if there is any.
func (c *FakeSyncs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(syncsResource, name), &v1alpha2.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Sync), err
}

// List takes label and field selectors, and returns the list of Syncs that match those selectors.
func (c *FakeSyncs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.SyncList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(syncsResource, syncsKind, opts), &v1alpha2.SyncList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.SyncList{ListMeta: obj.(*v1alpha2.SyncList).ListMeta}
	for _, item := range obj.(*v1alpha2.SyncList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested syncs.
func (c *FakeSyncs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(syncsResource, opts))
}

// Create takes the representation of a sync and creates it.  Returns the server's representation of the sync, and an error, if there is any.
func (c *FakeSyncs) Create(ctx context.Context, sync *v1alpha2.Sync, opts v1.CreateOptions) (result *v1alpha2.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(syncsResource, sync), &v1alpha2.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Sync), err
}

// Update takes the representation of a sync and updates it. Returns the server's representation of the sync, and an error, if there is any.
func (c *FakeSyncs) Update(ctx context.Context, sync *v1alpha2.Sync, opts v1.UpdateOptions) (result *v1alpha2.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(syncsResource, sync), &v1alpha2.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Sync), err
}

// Delete takes name of the sync and deletes it. Returns an error if one occurs.
func (c *FakeSyncs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(syncsResource, name), &v1alpha2.Sync{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSyncs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(syncsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.SyncList{})
	return err
}

// Patch applies the patch and returns the patched sync.
func (c *FakeSyncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(syncsResource, name, pt, data, subresources...), &v1alpha2.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Sync), err
}
