package market

// builtinCatalog returns a curated set of popular Olares apps.
// This is used as a fallback when the GitHub API is unreachable and
// no local catalog file exists. The data comes from the official
// beclab/apps repository OlaresManifest.yaml files.
func builtinCatalog() []MarketApp {
	return []MarketApp{
		{
			Name:        "wordpress",
			ChartName:   "wordpress",
			Title:       "WordPress",
			Description: "Blog Tool, Publishing Platform, and CMS",
			Icon:        "https://file.bttcdn.com/appstore/wordpress/icon.png",
			Version:     "1.0.15",
			VersionName: "6.4.2",
			Developer:   "WordPress",
			Categories:  []string{"Creativity", "Fun", "Social Network"},
			Website:     "https://wordpress.org/",
			SourceCode:  "https://github.com/wordpress/wordpress",
			Doc:         "https://wordpress.org/documentation/",
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Locale:      []string{"en-US", "zh-CN"},
			RequiredMemory: "1Gi",
			LimitedMemory:  "5Gi",
			RequiredDisk:   "1Gi",
			RequiredCPU:    "1",
			SupportArch:    []string{"amd64"},
			PromoteImage: []string{
				"https://file.bttcdn.com/appstore/wordpress/1.png",
				"https://file.bttcdn.com/appstore/wordpress/2.png",
				"https://file.bttcdn.com/appstore/wordpress/3.png",
			},
			Entrances: []Entrance{{Name: "wordpress", Host: "wordpresspublic", Port: 8080, Title: "WordPress", AuthLevel: "private"}},
			Permission: &AppPermission{AppData: true, AppCache: true},
			License:    []License{{Name: "GPLv2", URL: "https://wordpress.org/about/license/"}},
			FullDescription: "WordPress powers more than 43% of the web. Everything from simple websites, to blogs, to complex portals and enterprise websites, and even applications, are built with WordPress. WordPress combines simplicity for users and publishers with under-the-hood complexity for developers.",
		},
		{
			Name:        "gitea",
			ChartName:   "gitea",
			Title:       "Gitea",
			Description: "Git with a cup of tea!",
			Icon:        "https://app.cdn.olares.com/appstore/gitea/icon.png",
			Version:     "1.0.8",
			VersionName: "1.24.5",
			Developer:   "CommitGo, Inc",
			Categories:  []string{"Developer Tools", "Productivity", "Utilities"},
			Website:     "https://gitea.com",
			SourceCode:  "https://github.com/go-gitea/gitea",
			Doc:         "https://docs.gitea.com/",
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Locale:      []string{"en-US", "zh-CN"},
			RequiredMemory: "1Gi",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/gitea/1.webp",
				"https://app.cdn.olares.com/appstore/gitea/2.webp",
				"https://app.cdn.olares.com/appstore/gitea/3.webp",
			},
			Entrances: []Entrance{{Name: "gitea", Host: "gitea-web-svc", Port: 8080, Title: "Gitea", AuthLevel: "public"}},
			Permission: &AppPermission{AppData: true, AppCache: true, UserData: []string{"Home"}},
			License:    []License{{Name: "MIT License", URL: "https://github.com/go-gitea/gitea?tab=MIT-1-ov-file"}},
			FullDescription: "Gitea is a painless, self-hosted, all-in-one software development service. It includes Git hosting, code review, team collaboration, package registry, and CI/CD. It is similar to GitHub, Bitbucket and GitLab.",
		},
		{
			Name:        "jellyfin",
			ChartName:   "jellyfin",
			Title:       "Jellyfin",
			Description: "The Free Software Media System",
			Icon:        "https://app.cdn.olares.com/appstore/jellyfin/icon.png",
			Version:     "1.0.10",
			VersionName: "10.11.6",
			Categories:  []string{"Fun", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/jellyfin/promote_image_1v2.webp",
				"https://app.cdn.olares.com/appstore/jellyfin/promote_image_2v2.webp",
				"https://app.cdn.olares.com/appstore/jellyfin/promote_image_3v2.webp",
			},
			Permission: &AppPermission{AppData: true, AppCache: true, UserData: []string{"Home"}},
			FullDescription: "Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps.",
		},
		{
			Name:        "homeassistant",
			ChartName:   "homeassistant",
			Title:       "Home Assistant",
			Description: "Awaken your home",
			Icon:        "https://app.cdn.olares.com/appstore/homeassistant/icon.png",
			Version:     "1.0.13",
			VersionName: "2026.1.3",
			Categories:  []string{"Lifestyle", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/homeassistant/promote_image_1v2.webp",
				"https://app.cdn.olares.com/appstore/homeassistant/promote_image_2v2.webp",
				"https://app.cdn.olares.com/appstore/homeassistant/promote_image_3v2.webp",
			},
			Permission: &AppPermission{AppData: true, AppCache: true},
			FullDescription: "Home Assistant provides open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a local server.",
		},
		{
			Name:        "nextcloud",
			ChartName:   "nextcloud",
			Title:       "Nextcloud",
			Description: "The productivity platform that keeps you in control",
			Icon:        "https://app.cdn.olares.com/appstore/nextcloud/icon2.png",
			Version:     "1.0.11",
			VersionName: "31.0.4",
			Categories:  []string{"Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/nextcloud/1.webp",
				"https://app.cdn.olares.com/appstore/nextcloud/2.webp",
				"https://app.cdn.olares.com/appstore/nextcloud/3.webp",
			},
			Permission: &AppPermission{AppData: true, AppCache: true, UserData: []string{"Home"}},
			FullDescription: "Nextcloud puts your data at your fingertips, under your control. Store your documents, calendar, contacts and photos on a server at home, at one of our providers or in a data center you trust.",
		},
		{
			Name:        "immich",
			ChartName:   "immich",
			Title:       "Immich",
			Description: "High performance self-hosted photo and video management solution.",
			Icon:        "https://app.cdn.olares.com/appstore/immich/icon.png",
			Version:     "1.0.19",
			VersionName: "2.5.2",
			Categories:  []string{"Lifestyle", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/immich/01.png",
			},
			Entrances: []Entrance{{Name: "immich", Host: "immichclient", Port: 8080, Title: "Immich", AuthLevel: "internal"}},
			FullDescription: "Immich is a high performance self-hosted photo and video management solution. Upload, organize, and browse your photos and videos with a beautiful mobile app and web interface.",
		},
		{
			Name:        "n8n",
			ChartName:   "n8n",
			Title:       "n8n",
			Description: "n8n is an extendable workflow automation tool.",
			Icon:        "https://app.cdn.olares.com/appstore/n8n/icon.png",
			Version:     "1.0.14",
			Categories:  []string{"Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Permission:  &AppPermission{AppData: true, AppCache: true},
			FullDescription: "n8n is an extendable workflow automation tool. With a fair-code distribution model, n8n will always have visible source code, be available to self-host, and allow you to add your own custom functions, logic and apps.",
		},
		{
			Name:        "grafana",
			ChartName:   "grafana",
			Title:       "Grafana",
			Description: "Grafana is a multi-platform open source analytics and interactive visualization web application.",
			Icon:        "https://app.cdn.olares.com/appstore/grafana/icon.png",
			Version:     "1.0.11",
			VersionName: "12.1.4",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Permission:  &AppPermission{AppData: true, AppCache: true},
			FullDescription: "Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored. Create, explore, and share dashboards with your team and foster a data-driven culture.",
		},
		{
			Name:        "ollama",
			ChartName:   "ollama",
			Title:       "Ollama",
			Description: "Get up and running with large language models.",
			Icon:        "https://app.cdn.olares.com/appstore/ollama/icon.png",
			Version:     "1.1.16",
			Categories:  []string{"Utilities", "Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Ollama makes it easy to get up and running with large language models locally. Run Llama, Mistral, Gemma, and other open source models on your own hardware.",
		},
		{
			Name:        "openwebui",
			ChartName:   "openwebui",
			Title:       "Open WebUI",
			Description: "User-friendly WebUI for LLMs",
			Icon:        "https://app.cdn.olares.com/appstore/openwebui/icon.png",
			Version:     "1.0.21",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Open WebUI is a user-friendly WebUI for LLMs (formerly Ollama WebUI). It provides a ChatGPT-like interface for interacting with local language models through Ollama.",
		},
		{
			Name:        "lobechat",
			ChartName:   "lobechat",
			Title:       "LobeChat",
			Description: "An open-source, modern-design AI chat framework.",
			Icon:        "https://app.cdn.olares.com/appstore/lobechat/icon.png",
			Version:     "1.0.8",
			Categories:  []string{"Utilities", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "LobeChat is an open-source, modern-design AI chat framework. It supports multi-model providers, knowledge base, multi-modals, and extensible plugin system.",
		},
		{
			Name:        "ghost",
			ChartName:   "ghost",
			Title:       "Ghost",
			Description: "Independent technology for modern publishing, memberships, subscriptions and newsletters.",
			Icon:        "https://app.cdn.olares.com/appstore/ghost/icon.png",
			Version:     "1.0.10",
			Categories:  []string{"Creativity", "Fun", "Social Network"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Ghost is a powerful app for professional publishers to create, share, and grow a business around their content. It comes with modern tools to build a website, publish content, send newsletters & offer paid subscriptions to members.",
		},
		{
			Name:        "memos",
			ChartName:   "memos",
			Title:       "Memos",
			Description: "Effortlessly craft your impactful content.",
			Icon:        "https://app.cdn.olares.com/appstore/memos/icon.png",
			Version:     "1.0.9",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Permission:  &AppPermission{AppData: true, AppCache: true},
			FullDescription: "Memos is an open-source, lightweight note-taking solution. It allows you to effortlessly capture and share your great thoughts. Self-hosted with privacy first.",
		},
		{
			Name:        "uptimekuma",
			ChartName:   "uptimekuma",
			Title:       "Uptime Kuma",
			Description: "A fancy self-hosted monitoring tool",
			Icon:        "https://app.cdn.olares.com/appstore/uptimekuma/icon.png",
			Version:     "1.0.5",
			Categories:  []string{"Developer Tools", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Permission:  &AppPermission{AppData: true, AppCache: true},
			FullDescription: "Uptime Kuma is a fancy self-hosted monitoring tool. It supports monitoring uptime for HTTP(s), TCP, HTTP(s) Keywords, Ping, DNS, and more. Notifications via Telegram, Discord, Gotify, Slack, Pushover, and 90+ notification services.",
		},
		{
			Name:        "adguardhome",
			ChartName:   "adguardhome",
			Title:       "AdGuard Home",
			Description: "Network-wide ads & trackers blocking DNS server",
			Icon:        "https://app.cdn.olares.com/appstore/adguard/icon.png",
			Version:     "1.0.7",
			VersionName: "0.107.71",
			Categories:  []string{"Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/adguard/1.webp",
				"https://app.cdn.olares.com/appstore/adguard/2.webp",
				"https://app.cdn.olares.com/appstore/adguard/3.webp",
			},
			Permission: &AppPermission{AppData: true, AppCache: true, UserData: []string{"Home"}},
			FullDescription: "AdGuard Home is a network-wide software for blocking ads & tracking. It operates as a DNS server that re-routes tracking domains to a black hole, thus preventing your devices from connecting to those servers.",
		},
		{
			Name:        "audiobookshelf",
			ChartName:   "audiobookshelf",
			Title:       "AudioBookShelf",
			Description: "A self-hosted audiobook and podcast server.",
			Icon:        "https://app.cdn.olares.com/appstore/audiobookshelf/icon.png",
			Version:     "1.0.9",
			Categories:  []string{"Fun", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Entrances: []Entrance{{Name: "audiobookshelf", Host: "audiobookshelf", Port: 80, Title: "AudioBookShelf", AuthLevel: "private"}},
			FullDescription: "Audiobookshelf is a self-hosted audiobook and podcast server. It streams all audiobook formats and tracks your listening progress across devices.",
		},
		{
			Name:        "freshrss",
			ChartName:   "freshrss",
			Title:       "FreshRSS",
			Description: "A free, self-hostable feed aggregator.",
			Icon:        "https://app.cdn.olares.com/appstore/freshrss/icon.png",
			Version:     "1.0.4",
			VersionName: "1.28.1",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/freshrss/1.webp",
				"https://app.cdn.olares.com/appstore/freshrss/2.webp",
			},
			Permission: &AppPermission{AppData: true, AppCache: true, UserData: []string{"Home"}},
			FullDescription: "FreshRSS is a self-hosted RSS and Atom feed aggregator. It is lightweight, easy to work with, powerful, and customizable.",
		},
		{
			Name:        "calibreweb",
			ChartName:   "calibreweb",
			Title:       "Calibre-Web",
			Description: "Web app for browsing, reading and downloading eBooks stored in a Calibre database",
			Icon:        "https://app.cdn.olares.com/appstore/calibreweb/icon.png",
			Version:     "1.0.9",
			VersionName: "0.6.25",
			Categories:  []string{"Fun", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			PromoteImage: []string{
				"https://app.cdn.olares.com/appstore/calibreweb/promote_image_3.jpg",
				"https://app.cdn.olares.com/appstore/calibreweb/promote_image_1.jpg",
			},
			Permission: &AppPermission{AppData: true, AppCache: true, UserData: []string{"Home/Calibre"}},
			FullDescription: "Calibre-Web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.",
		},
		{
			Name:        "navidrome",
			ChartName:   "navidrome",
			Title:       "Navidrome",
			Description: "Your Personal Streaming Service",
			Icon:        "https://app.cdn.olares.com/appstore/navidrome/icon.png",
			Version:     "1.0.8",
			Categories:  []string{"Fun", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Entrances: []Entrance{{Name: "navidrome", Host: "navidrome", Port: 4533, Title: "Navidrome", AuthLevel: "private"}},
			FullDescription: "Navidrome is an open source web-based music collection server and streamer. It gives you freedom to listen to your music collection from any browser or mobile device. It's like your personal Spotify!",
		},
		{
			Name:        "dify",
			ChartName:   "dify",
			Title:       "Dify",
			Description: "The Innovation Engine for GenAI Applications",
			Icon:        "https://app.cdn.olares.com/appstore/dify/icon-new.png",
			Version:     "1.1.29",
			Categories:  []string{"Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Dify is an open-source LLM app development platform. Dify's intuitive interface combines AI workflow, RAG pipeline, agent capabilities, model management, observability features and more, letting you quickly go from prototype to production.",
		},
		{
			Name:        "photoprism",
			ChartName:   "photoprism",
			Title:       "PhotoPrism",
			Description: "AI-Powered Photos App for the Decentralized Web",
			Icon:        "https://app.cdn.olares.com/appstore/photoprism/icon.png",
			Version:     "1.0.13",
			Categories:  []string{"Lifestyle", "Entertainment"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Permission:  &AppPermission{AppData: true, AppCache: true},
			FullDescription: "PhotoPrism is an AI-powered app for browsing, organizing & sharing your photo collection. It makes use of the latest technologies to tag and find pictures automatically without getting in your way.",
		},
		{
			Name:        "filebrowser",
			ChartName:   "filebrowser",
			Title:       "Filebrowser",
			Description: "Upload, delete, preview, rename, edit and share your files",
			Icon:        "https://file.bttcdn.com/appstore/filebrowser/icon.png",
			Version:     "1.0.1",
			Categories:  []string{"Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "File Browser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It supports multiple users and each user can have its own directory.",
		},
		{
			Name:        "searxng",
			ChartName:   "searxng",
			Title:       "SearXNG",
			Description: "Search without being tracked.",
			Icon:        "https://app.cdn.olares.com/appstore/searxng/icon.png",
			Version:     "1.0.13",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "SearXNG is a free internet metasearch engine which aggregates results from various search services and databases. Users are neither tracked nor profiled. Privacy-respecting, hackable metasearch engine.",
		},
		{
			Name:        "penpot",
			ChartName:   "penpot",
			Title:       "Penpot",
			Description: "Penpot is the web-based open-source design tool that bridges the gap between designers and developers.",
			Icon:        "https://app.cdn.olares.com/appstore/penpot/icon.png",
			Version:     "1.0.10",
			Categories:  []string{"Creativity", "Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			Permission:  &AppPermission{AppData: true, AppCache: true},
			FullDescription: "Penpot is the first open-source design tool for design and code collaboration. Designers can create stunning designs, interactive prototypes, design systems at scale, while developers enjoy ready-to-use code and objects without handoff hassles.",
		},
		{
			Name:        "stirlingpdf",
			ChartName:   "stirlingpdf",
			Title:       "Stirling PDF",
			Description: "Locally hosted web based PDF manipulation tool",
			Icon:        "https://app.cdn.olares.com/appstore/stirlingpdf/icon.png",
			Version:     "1.0.5",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Stirling PDF is a locally hosted web application that allows you to perform various operations on PDF files, including splitting, merging, converting, reorganizing, adding images, rotating, compressing, and more.",
		},
		{
			Name:        "excalidraw",
			ChartName:   "excalidraw",
			Title:       "Excalidraw",
			Description: "Virtual whiteboard for sketching hand-drawn like diagrams",
			Icon:        "https://app.cdn.olares.com/appstore/excalidraw/icon.png",
			Version:     "1.0.3",
			Categories:  []string{"Creativity", "Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Excalidraw is a virtual collaborative whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them. It supports real-time collaboration and end-to-end encryption.",
		},
		{
			Name:        "halo",
			ChartName:   "halo",
			Title:       "Halo",
			Description: "Powerful and easy-to-use open source website building tool",
			Icon:        "https://app.cdn.olares.com/appstore/halo/icon.png",
			Version:     "1.0.5",
			Categories:  []string{"Creativity", "Social Network"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Halo is a powerful and easy-to-use open source website building tool, making it easy for you to have a blog of your own. It is a modern open-source blogging/CMS platform.",
		},
		{
			Name:        "codeserver",
			ChartName:   "codeserver",
			Title:       "Code Server",
			Description: "Run VS Code on any machine anywhere and access it in the browser",
			Icon:        "https://app.cdn.olares.com/appstore/codeserver/icon.png",
			Version:     "1.0.5",
			Categories:  []string{"Developer Tools", "Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Code Server runs VS Code on any machine anywhere and access it in the browser. Code on any device with a consistent development environment.",
		},
		{
			Name:        "miniflux",
			ChartName:   "miniflux",
			Title:       "Miniflux",
			Description: "Minimalist and opinionated feed reader",
			Icon:        "https://app.cdn.olares.com/appstore/miniflux/icon.png",
			Version:     "1.0.3",
			Categories:  []string{"Productivity", "Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Miniflux is a minimalist and opinionated feed reader. It's simple, fast, lightweight and super easy to install. Supports RSS, Atom, RDF and JSON feeds.",
		},
		{
			Name:        "transmission",
			ChartName:   "transmission",
			Title:       "Transmission",
			Description: "A fast, easy, free BitTorrent client",
			Icon:        "https://app.cdn.olares.com/appstore/transmission/icon.png",
			Version:     "1.0.4",
			Categories:  []string{"Utilities"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "Transmission is a fast, easy, and free multi-platform BitTorrent client. It comes with useful features like web interface, peer exchange, magnet link support, DHT, encryption, and more.",
		},
		{
			Name:        "ragflow",
			ChartName:   "ragflow",
			Title:       "RAGFlow",
			Description: "Open-source RAG engine based on deep document understanding",
			Icon:        "https://app.cdn.olares.com/appstore/ragflow/icon.png",
			Version:     "1.0.5",
			Categories:  []string{"Productivity"},
			Source:      "olares",
			Status:      "active",
			Type:        "app",
			CfgType:     "app",
			FullDescription: "RAGFlow is an open-source RAG (Retrieval-Augmented Generation) engine based on deep document understanding. It combines template-based chunking with LLM-powered understanding for grounded answers with well-founded citations.",
		},
	}
}
