// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api_account "integration/pkg/hertz/biz/router/api/account"
	api_cookie "integration/pkg/hertz/biz/router/api/cookie"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	api_cookie.Register(r)

	api_account.Register(r)
}
