apiVersion: v1
kind: Service
metadata:
  name: vllm-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    io.kompose.service: vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000
