package systemserver

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const nginxServerBlockTemplate = `# Auto-generated by packalares system-server for app: {{.AppName}}
# Entrance: {{.EntranceName}}
# Do not edit manually.

server {
    listen 80;
    server_name {{.ServerName}};

    location / {
{{- if .AuthRequired}}
        auth_request /api/verify;
        auth_request_set $auth_user $upstream_http_remote_user;
        auth_request_set $auth_groups $upstream_http_remote_groups;
        error_page 401 = @auth_redirect;
{{- end}}

        proxy_pass http://{{.UpstreamHost}}:{{.UpstreamPort}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
{{- if .AuthRequired}}
        proxy_set_header Remote-User $auth_user;
        proxy_set_header Remote-Groups $auth_groups;
{{- end}}

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_buffering off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

{{- if .AuthRequired}}
    location = /api/verify {
        internal;
        proxy_pass http://authelia-backend-svc:9091/api/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URL $scheme://$host$request_uri;
        proxy_set_header X-Forwarded-Host $host;
    }

    location @auth_redirect {
        return 302 https://auth.{{.UserZone}}/?rd=$scheme://$host$request_uri;
    }
{{- end}}
}
`

type NginxGenerator struct {
	configPath string
	reloadCmd  string
	userZone   string
}

type nginxTemplateData struct {
	AppName       string
	EntranceName  string
	ServerName    string
	UpstreamHost  string
	UpstreamPort  int
	UserZone      string
	AuthRequired  bool
}

func NewNginxGenerator(configPath, reloadCmd, userZone string) *NginxGenerator {
	return &NginxGenerator{
		configPath: configPath,
		reloadCmd:  reloadCmd,
		userZone:   userZone,
	}
}

// GenerateForApp creates nginx config files for all entrances of an app.
func (g *NginxGenerator) GenerateForApp(app *Application) error {
	if err := os.MkdirAll(g.configPath, 0755); err != nil {
		return fmt.Errorf("create nginx config directory: %w", err)
	}

	for _, entrance := range app.Spec.Entrances {
		if entrance.Invisible {
			continue
		}

		serverName := entrance.Host
		if serverName == "" {
			// Default: entranceName.userZone
			serverName = fmt.Sprintf("%s.%s", entrance.Name, g.userZone)
		}

		authRequired := true
		switch strings.ToLower(entrance.AuthLevel) {
		case "public":
			authRequired = false
		}

		upstreamHost := fmt.Sprintf("%s.%s.svc.cluster.local", app.Spec.Name, app.Spec.Namespace)

		data := nginxTemplateData{
			AppName:      app.Spec.Name,
			EntranceName: entrance.Name,
			ServerName:   serverName,
			UpstreamHost: upstreamHost,
			UpstreamPort: entrance.Port,
			UserZone:     g.userZone,
			AuthRequired: authRequired,
		}

		filename := fmt.Sprintf("%s-%s.conf", app.Spec.Name, entrance.Name)
		configFile := filepath.Join(g.configPath, filename)

		if err := g.writeConfig(configFile, data); err != nil {
			return fmt.Errorf("write nginx config for %s/%s: %w", app.Spec.Name, entrance.Name, err)
		}

		log.Printf("generated nginx config %s (server_name=%s, upstream=%s:%d, auth=%v)",
			filename, serverName, upstreamHost, entrance.Port, authRequired)
	}

	return nil
}

// RemoveForApp deletes nginx config files for an app.
func (g *NginxGenerator) RemoveForApp(appName string) error {
	pattern := filepath.Join(g.configPath, appName+"-*.conf")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return fmt.Errorf("glob nginx configs: %w", err)
	}

	for _, f := range matches {
		if err := os.Remove(f); err != nil {
			log.Printf("remove nginx config %s: %v", f, err)
		} else {
			log.Printf("removed nginx config %s", f)
		}
	}

	return nil
}

// Reload triggers an nginx reload.
func (g *NginxGenerator) Reload() error {
	if g.reloadCmd == "" {
		return nil
	}

	parts := strings.Fields(g.reloadCmd)
	cmd := exec.Command(parts[0], parts[1:]...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("nginx reload: %s: %w", string(out), err)
	}

	log.Println("nginx reloaded successfully")
	return nil
}

func (g *NginxGenerator) writeConfig(path string, data nginxTemplateData) error {
	tmpl, err := template.New("nginx").Parse(nginxServerBlockTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, data)
}
