location /api/auth/login  { proxy_pass http://$auth_up:9091/api/firstfactor; proxy_set_header Host $host; proxy_set_header Cookie $http_cookie; }
location = /api/auth/totp { proxy_pass http://$auth_up:9091/api/secondfactor/totp; proxy_set_header Host $host; proxy_set_header Cookie $http_cookie; }
location /api/auth/state  { proxy_pass http://$auth_up:9091/api/state; proxy_set_header Cookie $http_cookie; }
location /api/auth/logout { proxy_pass http://$auth_up:9091/api/logout; proxy_set_header Cookie $http_cookie; }
location /api/auth/health { proxy_pass http://$auth_up:9091/api/health; }
location /api/user/info   { proxy_pass http://$bfl_up:80/bfl/backend/v1/user-info; proxy_set_header Host $host; }
location /bfl/info/v1/    { proxy_pass http://$bfl_up:80; proxy_set_header Host $host; }
location /bfl/settings/v1alpha1/activate { proxy_pass http://$bfl_up:80; proxy_set_header Host $host; proxy_set_header Cookie $http_cookie; }
location /bfl/settings/v1alpha1/binding-zone { proxy_pass http://$bfl_up:80; proxy_set_header Host $host; proxy_set_header Cookie $http_cookie; }
location /bfl/iam/ { proxy_pass http://$bfl_up:80; proxy_set_header Host $host; proxy_set_header Cookie $http_cookie; }
