location /js/    { proxy_pass http://$desktop_up:80; }
location /css/   { proxy_pass http://$desktop_up:80; }
location /fonts/ { proxy_pass http://$desktop_up:80; }
location /icons/ { proxy_pass http://$desktop_up:80; }
location /bg/    { proxy_pass http://$desktop_up:80; }
location /avatar-default.png { proxy_pass http://$desktop_up:80; }
location ~ ^/(?!api/)[^/]*\.(js|css|map|ico|png|jpg|svg|woff2?)$ { proxy_pass http://$desktop_up:80; }
