set $auth_up auth-backend.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $bfl_up bfl.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $desktop_up desktop-svc.{{USER_NAMESPACE}}.svc.cluster.local;
set $files_up files-server.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $market_up market-backend.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $app_up app-service.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $mon_up monitoring-server.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $mounts_up mounts-server.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
set $ss_up system-server.{{FRAMEWORK_NAMESPACE}}.svc.cluster.local;
