// Code generated by hertz generator.

package account

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
