

# Build the manager binary
FROM golang:1.23 as builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN apt update && apt install -y libudev-dev libpcap-dev
RUN \
	echo ">> Downloading go modules..." && \
	go mod download

COPY / ./

RUN GGO_ENABLED=0 go build -ldflags="-s -w" -o mdns-agent cmd/mdns_agent/main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
# FROM gcr.io/distroless/base:nonroot
FROM gcr.io/distroless/base:debug
WORKDIR /
COPY --from=builder /workspace/mdns-agent .

EXPOSE 5353

ENTRYPOINT ["/mdns-agent"]