// Code generated by hertz generator.

package account

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"integration/pkg/constant"
	"integration/pkg/hertz/biz/handler"
	account "integration/pkg/hertz/biz/model/api/account"
	"integration/pkg/hertz/biz/model/api/infisical"
	"integration/pkg/utils"

	"k8s.io/klog/v2"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/emicklei/go-restful/v3"
)

// GetAccount .
// @router /api/account/retrieve [POST]
func GetAccount(ctx context.Context, c *app.RequestContext) { // +
	var err error
	var req account.AccountReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	var name = fmt.Sprintf("integration-account:%s:%s", req.Type, req.Name)
	var data = make(map[string]string)
	data["name"] = name
	data["env"] = constant.Environment
	var infisicalUrl = fmt.Sprintf("%s:%s/RetrieveSecret?workspace=%s", constant.InfisicalAddr, constant.InfisicalPort, constant.Workspace)

	resp, err := utils.RestClient.R().SetHeader(restful.HEADER_ContentType, restful.MIME_JSON).
		SetHeader(constant.HeaderUserName, req.User).
		SetBody(data).
		SetResult(&infisical.InfisicalResp{}).
		Post(infisicalUrl)

	if err != nil {
		klog.Errorf("GetAccount failed, request error: %v, account: %s", err, name)
		handler.ErrorResponse(c, err)
		return
	}

	if resp.StatusCode() != http.StatusOK {
		klog.Errorf("GetAccount failed, status code: %d, resp: %s", resp.StatusCode(), string(resp.Body()))
		handler.ErrorResponse(c, fmt.Errorf("request invalid, status code: %d", resp.StatusCode()))
		return
	}

	accountResp := resp.Result().(*infisical.InfisicalResp)
	var result = &account.AccountResp{}

	if accountResp.Code != 0 {
		err := handler.FormatErrorMessage(accountResp.Message)
		klog.Errorf("GetAccount failed, format error: %v, content: %s", err, accountResp.Message)
		handler.ErrorResponse(c, err)
		return
	}

	accountType, accountName, err := getAccountName(accountResp.Data.Name)
	if err != nil {
		klog.Errorf("GetAccount failed, extract acount info error: %v", err)
		handler.ErrorResponse(c, err)
		return
	}

	valueObj, err := unmarshalValue(accountResp.Data.Value)
	if err != nil {
		klog.Errorf("GetAccount failed, unmarshal error: %v, content: %s", err, accountResp.Data.Value)
		handler.ErrorResponse(c, err)
		return
	}

	var rawData = &account.AccountRespDataRaw{
		ExpiresAt:    valueObj.ExpiresAt,
		RefreshToken: valueObj.RefreshToken,
		AccessToken:  valueObj.AccessToken,
		Endpoint:     valueObj.Endpoint,
		Bucket:       valueObj.Bucket,
		UserId:       valueObj.UserId,
		Available:    valueObj.Available,
		CreateAt:     valueObj.CreateAt,
		Scope:        valueObj.Scope,
		IdToken:      valueObj.IdToken,
		ClientId:     valueObj.ClientId,
	}

	result.Data = &account.AccountRespData{
		Name:    accountName,
		Type:    accountType,
		RawData: rawData,
	}

	c.JSON(consts.StatusOK, result)
}

// GetList .
// @router /api/account/list [POST]
func GetList(ctx context.Context, c *app.RequestContext) { // +
	var err error
	var req account.AccountListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	var data = make(map[string]string)
	data["env"] = constant.Environment
	var infisicalUrl = fmt.Sprintf("%s:%s/ListSecret?workspace=%s", constant.InfisicalAddr, constant.InfisicalPort, constant.Workspace)

	resp, err := utils.RestClient.R().SetHeader(restful.HEADER_ContentType, restful.MIME_JSON).
		SetHeader(constant.HeaderUserName, req.User).
		SetBody(data).
		SetResult(&infisical.InfisicalListResp{}).
		Post(infisicalUrl)

	if err != nil {
		klog.Errorf("GetList failed, request error: %v", err)
		handler.ErrorResponse(c, err)
		return
	}

	if resp.StatusCode() != http.StatusOK {
		klog.Errorf("GetList failed, status code: %d, resp: %s", resp.StatusCode(), string(resp.Body()))
		handler.ErrorResponse(c, fmt.Errorf("request invalid, status code: %d", resp.StatusCode()))
		return
	}

	infisicalListResp := resp.Result().(*infisical.InfisicalListResp)

	if infisicalListResp.Code != 0 {
		err := handler.FormatErrorMessage(infisicalListResp.Message)
		klog.Errorf("GetList failed, format error: %v, content: %s", err, infisicalListResp.Message)
		handler.ErrorResponse(c, err)
		return
	}

	var datas []*account.AccountListData
	for _, item := range infisicalListResp.Data {
		if !strings.HasPrefix(item.Name, "integration-account:") {
			continue
		}
		accountType, accountName, err := getAccountName(item.Name)
		if err != nil {
			klog.Errorf("GetList failed, get accountInfo error: %v, name: %s", err, item.Name)
			handler.ErrorResponse(c, err)
			return
		}
		valueObj, err := unmarshalValue(item.Value)
		if err != nil {
			klog.Errorf("GetList failed, unmarshale error: %v, name: %s", err, item.Value)
			handler.ErrorResponse(c, err)
			return
		}

		var raw = &account.AccountListData{
			Name:      accountName,
			Type:      accountType,
			Available: valueObj.Available,
			CreateAt:  valueObj.CreateAt,
			ExpiresAt: valueObj.ExpiresAt,
		}
		datas = append(datas, raw)
	}

	var result = &account.AccountListResp{
		Code: 0,
		Data: datas,
	}

	c.JSON(consts.StatusOK, result)
}

func getAccountName(fullName string) (string, string, error) {
	var tmp = strings.Split(fullName, ":")
	if len(tmp) == 3 {
		return tmp[1], tmp[2], nil
	}
	return "", "", fmt.Errorf("account type invalid")
}

func unmarshalValue(value string) (*infisical.AccountDataRaw, error) {
	var valueObj *infisical.AccountDataRaw
	if err := json.Unmarshal([]byte(value), &valueObj); err != nil {
		return nil, err
	}
	return valueObj, nil
}
