// Code generated by hertz generator.

package cookie

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cookieMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcookieMw() []app.HandlerFunc {
	// your code...
	return nil
}
